baseURL = "https://bgottlob.com"
languageCode = "en-us"
title = "Brandon Gottlob"
theme = "etch"

[params]
  copyright = "Copyright 2023 Brandon Gottlob"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "https://bgottlob-public.us-east-1.linodeobjects.com/bgottlob_resume.pdf"
    weight = "10"

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/bgottlob"
    weight = "20"

  [[menu.main]]
    identifier = "rss"
    name = "rss"
    title = "rss"
    url = "/index.xml"
    weight = "30"
