baseURL = "https://bgottlob.com"
languageCode = "en-us"
title = "Brandon Gottlob"
theme = "etch"

[params]
  copyright = "Copyright 2021 Brandon Gottlob"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/bgottlob_resume.pdf"
    weight = "10"

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/bgottlob"
    weight = "20"
